<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>accept_PDPA</name>
   <tag></tag>
   <elementGuidId>0fd365fc-9c37-4167-8f5d-596a6d646c60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='question_element']//div[2]//label[1]//label[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='question_element']//div[2]//label[1]//label[1]</value>
   </webElementProperties>
</WebElementEntity>
