<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_choice</name>
   <tag></tag>
   <elementGuidId>45941732-39ee-4f0d-ab90-b9bcada74dd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='choices']//div[1]//div[${buff}]//label[1]//label[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='choices']//div[1]//div[${buff}]//label[1]//label[1]</value>
   </webElementProperties>
</WebElementEntity>
